project:
  type: website

website:
  title: "Luis Miguel Díaz Pichardo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research/
        text: Research
      - href: publications/
        text: Publications
      - href: projects/
        text: Projects
      - href: about/
        text: About
    right:
      - icon: github
        href: https://github.com/Rhobtor
      - icon: linkedin
        href: https://www.linkedin.com/in/luis-miguel-diaz-pichardo-2255b3180/
      - icon: envelope
        href: mailto:luismidp7@gmail.com

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true